/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.EmployeeEngagement;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Company;
import Business.Course.CourseCatalog;
import Business.Course.CourseOffering;
import Business.User.User;
import Business.User.UserManager;
import UserInterface.MainFrame;

/**
 *
 * @author nivcodes
 */
public class EmployeeLandingPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeLandingPanel
     */
    UserManager userManager;
    User current_user;
    CourseCatalog courseCatalog;
    Company c;
    ArrayList<CourseOffering> coList = new ArrayList<>();
    public EmployeeLandingPanel(ArrayList<CourseOffering> coList, Company c, CourseCatalog courseCatalog, UserManager userManager, User current_user) {
        initComponents();
        this.userManager = userManager;
        this.current_user = current_user;
        this.courseCatalog = courseCatalog;
        this.c = c;
        this.coList = coList;
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeeFb = new javax.swing.JTable();
        lblCmpName = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Center");

        tblEmployeeFb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course", "Professor", "Speciality", "Term"
            }
        ));
        jScrollPane1.setViewportView(tblEmployeeFb);

        lblCmpName.setText("company name");

        btnDetails.setBackground(new java.awt.Color(153, 204, 255));
        btnDetails.setText("View details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblCmpName)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblCmpName)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEmployeeFb.getSelectedRow();
//        
        if (selectedRowIndex<0) { 
            JOptionPane.showMessageDialog(this, "Please select a row to be displayed.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblEmployeeFb.getModel();
        CourseOffering co = (CourseOffering) model.getValueAt(selectedRowIndex, 0);
        EmployeeCoursePanel detailPanel = new EmployeeCoursePanel(co, c, userManager, current_user);
        MainFrame.mfInstance.setMainframeSplitFrame(detailPanel);
    }//GEN-LAST:event_btnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCmpName;
    private javax.swing.JTable tblEmployeeFb;
    // End of variables declaration//GEN-END:variables
    public void fillData(){
        DefaultTableModel model = (DefaultTableModel) tblEmployeeFb.getModel();
        model.setRowCount(0);
        for (CourseOffering co : coList){
            
            
            Object[] row = new Object[4];
            row[0] = co;
            row[1] = co.getProfessor();
            row[2] = co.getProfessor().getSpecialty();
            row[3] = co.getTerm().getName();

            model.addRow(row);
        }
        lblCmpName.setText("Welcome, "+ c.getName() + "from " + c.getLocation());
    }
}
