/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.EmployeeEngagement;

import java.util.ArrayList;
import Business.Company;
import Business.Course.CourseCatalog;
import Business.Course.CourseOffering;
import Business.User.User;
import Business.User.UserManager;
import UserInterface.MainFrame;

/**
 *
 * @author nivcodes
 */
public class EmployeeCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeCoursePanel
     */
    UserManager userManager;
    User current_user;
    Company c;
    CourseOffering co;
    public EmployeeCoursePanel(CourseOffering co, Company c, UserManager userManager, User current_user) {
        initComponents();
        this.userManager = userManager;
        this.current_user = current_user;
        this.c = c;
        this.co = co;
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblname1 = new javax.swing.JLabel();
        lblAssignedTerm = new javax.swing.JLabel();
        lblname2 = new javax.swing.JLabel();
        lblAssignedRanking = new javax.swing.JLabel();
        lblname3 = new javax.swing.JLabel();
        lblAssignedPName = new javax.swing.JLabel();
        lblname4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblname5 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblAssignedschedule = new javax.swing.JLabel();
        lblAssignedCName = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        btnAddRating = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname1.setText("Term:");

        lblAssignedTerm.setText("name");

        lblname2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname2.setText("Ranking:");

        lblAssignedRanking.setText("name");

        lblname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname3.setText("Professor name:");

        lblAssignedPName.setText("name");

        lblname4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname4.setText("Professor rating:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Details");

        lblname5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname5.setText("schedule:");

        lblname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname.setText("Name:");

        lblAssignedschedule.setText("name");

        lblAssignedCName.setText("name");

        btnAddRating.setBackground(new java.awt.Color(153, 204, 255));
        btnAddRating.setText("Add Rating");
        btnAddRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRatingActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnBack)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedCName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblname3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblname4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAssignedPName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnAddRating, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(lblAssignedCName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname1)
                    .addComponent(lblAssignedTerm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname2)
                    .addComponent(lblAssignedRanking))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname3)
                    .addComponent(lblAssignedPName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname4)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname5)
                    .addComponent(lblAssignedschedule))
                .addGap(26, 26, 26)
                .addComponent(btnAddRating, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRatingActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(txtRating.getText());
        co.getProfessor().addRating(a);
        txtRating.setText(String.valueOf(co.getProfessor().getRating()) + " (" + co.getProfessor().RatingCount() + " ratings)");
    }//GEN-LAST:event_btnAddRatingActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainFrame.mfInstance.setLandingPage(current_user);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRating;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAssignedCName;
    private javax.swing.JLabel lblAssignedPName;
    private javax.swing.JLabel lblAssignedRanking;
    private javax.swing.JLabel lblAssignedTerm;
    private javax.swing.JLabel lblAssignedschedule;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname3;
    private javax.swing.JLabel lblname4;
    private javax.swing.JLabel lblname5;
    private javax.swing.JTextField txtRating;
    // End of variables declaration//GEN-END:variables
    
    public void fillData(){
        lblAssignedCName.setText(co.getCourseName());
        lblAssignedPName.setText(co.getProfessor().getName());
        lblAssignedRanking.setText(String.valueOf(co.getRanking()));
        lblAssignedTerm.setText(co.getTerm().getName());
        lblAssignedschedule.setText(co.getSchedule());
        txtRating.setText(String.valueOf(co.getProfessor().getRating()) + " (" + co.getProfessor().RatingCount() + " ratings)");
    }
}
