/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.StudentRole;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Course.CourseOffering;
import Business.Student.SCHistoryManager;
import Business.Student.StudentCourseHistory;
import Business.Course.Term;
import Business.User.User;
import Business.User.UserManager;
import UserInterface.MainFrame;

/**
 *
 * @author nivcodes
 */
public class MycoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MycoursesJPanel
     */
    SCHistoryManager scHisManager;
    Term term;
    UserManager userManager;
    User current_user;
    StudentCourseHistory stch;
    public MycoursesJPanel(SCHistoryManager scHisManager, Term term, UserManager userManager, User current_user) {
        initComponents();
        this.userManager = userManager;
        this.current_user = current_user;
        this.term = term;
        this.scHisManager = scHisManager;
        stch = scHisManager.findHistory(current_user);
    
        populateDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSpring2023 = new javax.swing.JButton();
        btnFall2023 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course", "Ranking", "Grade", "Term"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Courses");

        lblGPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPA.setText(" ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Get transcript for term :");

        btnSpring2023.setBackground(new java.awt.Color(153, 204, 255));
        btnSpring2023.setText("Spring 2023");
        btnSpring2023.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpring2023ActionPerformed(evt);
            }
        });

        btnFall2023.setBackground(new java.awt.Color(153, 204, 255));
        btnFall2023.setText("Fall 2023");
        btnFall2023.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFall2023ActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSpring2023)
                            .addGap(18, 18, 18)
                            .addComponent(btnFall2023)
                            .addGap(14, 14, 14)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(444, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFall2023, btnSpring2023});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGPA)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpring2023, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFall2023)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFall2023, btnSpring2023});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSpring2023ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpring2023ActionPerformed
        // TODO add your handling code here:
        TranscriptJPanel cbPanel = new TranscriptJPanel("Spring 2023", stch,current_user, userManager);
        MainFrame.mfInstance.setMainframeSplitFrame(cbPanel);
    }//GEN-LAST:event_btnSpring2023ActionPerformed

    private void btnFall2023ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFall2023ActionPerformed
        // TODO add your handling code here:
        TranscriptJPanel cbPanel = new TranscriptJPanel("Fall 2023", stch,current_user, userManager);
        MainFrame.mfInstance.setMainframeSplitFrame(cbPanel);
    }//GEN-LAST:event_btnFall2023ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainFrame.mfInstance.setLandingPage(current_user);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFall2023;
    private javax.swing.JButton btnSpring2023;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables

    private void populateDetails(){
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        for (CourseOffering co : stch.getCourseWork()){
            
            
            Object[] row = new Object[4];
            row[0] = co;
            row[1] = co.getRanking();
            row[2] = FormatGrade(stch.getFinalGrade(co));
            row[3] = co.getTerm().getName();

            model.addRow(row);
        }
        Double gpa = stch.getGPA();
        lblGPA.setText("Your projected GPA is "+FormatGrade(gpa));
    }
    
    public String FormatGrade(Double a){
        if (a != 0.00){
            return String.format("%.2f",a);
        }else{
            return "Ongoing";
        }
    }
}
