/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.StudentRole;

import javax.swing.JOptionPane;
import Business.Student.SCHistoryManager;
import Business.Student.StudentCourseHistory;
import Business.Course.Term;
import Business.User.User;
import Business.User.UserManager;
import UserInterface.MainFrame;

/**
 *
 * @author Sanskruti  <your.name at your.org>
 */
public class StudentLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentMenuJPanel
     */
    UserManager userManager;
    User current_user;
    Term term;
    SCHistoryManager scHisManager;
    public StudentLandingJPanel(SCHistoryManager scHisManager, Term term, UserManager userManager, User current_user) {
        initComponents();
        this.userManager = userManager;
        this.current_user = current_user;
        this.term = term;
        this.scHisManager = scHisManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewMyCourses = new javax.swing.JButton();
        lbltitle1 = new javax.swing.JLabel();
        btnViewAllCourses = new javax.swing.JButton();
        btnCalulateGPA = new javax.swing.JButton();
        btnRequestGraduate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 900));

        btnViewMyCourses.setBackground(new java.awt.Color(153, 204, 255));
        btnViewMyCourses.setText("My Courses");
        btnViewMyCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyCoursesActionPerformed(evt);
            }
        });

        lbltitle1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbltitle1.setText("Student Landing Page");

        btnViewAllCourses.setBackground(new java.awt.Color(153, 204, 255));
        btnViewAllCourses.setText("View all offered courses");
        btnViewAllCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllCoursesActionPerformed(evt);
            }
        });

        btnCalulateGPA.setBackground(new java.awt.Color(153, 204, 255));
        btnCalulateGPA.setText("Calculate GPA");
        btnCalulateGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalulateGPAActionPerformed(evt);
            }
        });

        btnRequestGraduate.setBackground(new java.awt.Color(153, 204, 255));
        btnRequestGraduate.setText("Request to graduate");
        btnRequestGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestGraduateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewAllCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRequestGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewMyCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalulateGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(lbltitle1)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lbltitle1)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewMyCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAllCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalulateGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMyCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyCoursesActionPerformed
        // TODO add your handling code here
        MycoursesJPanel cbPanel = new MycoursesJPanel(scHisManager, term, userManager, current_user);
        MainFrame.mfInstance.setMainframeSplitFrame(cbPanel);
        
    }//GEN-LAST:event_btnViewMyCoursesActionPerformed

    private void btnViewAllCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllCoursesActionPerformed
        // TODO add your handling code here:
        CourseBrowseJPanel cbPanel = new CourseBrowseJPanel(term, userManager, current_user);
        MainFrame.mfInstance.setMainframeSplitFrame(cbPanel);
    }//GEN-LAST:event_btnViewAllCoursesActionPerformed

    private void btnCalulateGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalulateGPAActionPerformed
        // TODO add your handling code here:
        StudentCourseHistory stch = scHisManager.findHistory(current_user);
        Double gpa = stch.getGPA();
        JOptionPane.showMessageDialog(this, "Your calculated GPA is "+ String.format("%.2f",gpa));
    }//GEN-LAST:event_btnCalulateGPAActionPerformed

    private void btnRequestGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestGraduateActionPerformed
        // TODO add your handling code here:
        StudentCourseHistory stch = scHisManager.findHistory(current_user);
        //JOptionPane.showMessageDialog(this, stch.getcompletedCourseCount());
        if (stch.getcompletedCourseCount() >= 8){
            MainFrame.mfInstance.gradRequest.add(stch);
            JOptionPane.showMessageDialog(this, "Congrats! You are eligible to graduate with " + stch.getGPA() + ". Request approved!");
        }else {
            JOptionPane.showMessageDialog(this, "You still have "+ (8-stch.getCourseCount()) + " courses to complete to get your degree.");
        }
    }//GEN-LAST:event_btnRequestGraduateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalulateGPA;
    private javax.swing.JButton btnRequestGraduate;
    private javax.swing.JButton btnViewAllCourses;
    private javax.swing.JButton btnViewMyCourses;
    private javax.swing.JLabel lbltitle1;
    // End of variables declaration//GEN-END:variables
}
