/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.CertificationAuthority;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Course.CourseOffering;
import Business.Student.StudentCourseHistory;
import Business.User.User;
import Business.User.UserManager;

/**
 *
 * @author Sanskruti  <your.name at your.org>
 */
public class CertificateAuthorityLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentMenuJPanel
     */
    UserManager userManager;
    User current_user;
    ArrayList<StudentCourseHistory> gradRequest = new ArrayList<>();
    public CertificateAuthorityLandingJPanel(ArrayList<StudentCourseHistory> gradRequest, UserManager userManager, User current_user) {
        initComponents();
        this.userManager = userManager;
        this.current_user = current_user;
        this.gradRequest = gradRequest;
        populateData();
        System.out.println(gradRequest.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 900));

        lbltitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbltitle.setText("Certificate Authority");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student name", "Approved?", "CourseLoad"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        btnApprove.setBackground(new java.awt.Color(153, 204, 255));
        btnApprove.setText("Approve Student to graduate");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lbltitle)))
                .addContainerGap(595, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbltitle)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(503, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblStudents.getSelectedRow();
//        
        if (selectedRowIndex<0) { 
            JOptionPane.showMessageDialog(this, "Please select a row to approve.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        StudentCourseHistory co = (StudentCourseHistory) model.getValueAt(selectedRowIndex, 0);
        co.approveStudent();
        JOptionPane.showMessageDialog(this, "Approved!");
    }//GEN-LAST:event_btnApproveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables

    public void populateData(){
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);
        for (StudentCourseHistory co : gradRequest){
            
            
            Object[] row = new Object[3];
            row[0] = co;
            row[1] = co.isApproved();
            row[2] = String.valueOf(co.getCourseCount());

            model.addRow(row);
        }
    }
}
