/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Course.CourseOffering;
import Business.Course.Term;
import Business.User.User;
import Business.User.UserManager;
import UserInterface.MainFrame;
import static UserInterface.MainFrame.mfInstance;

/**
 *
 * @author nivcodes
 */
public class CourseDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form CourseDetailForm
     */
    UserManager userManager;
    User current_user;
    Term term;
    CourseOffering co;
    public CourseDetailForm(Term term, UserManager userManager, User current_user, CourseOffering co) {
        initComponents();
        this.userManager = userManager;
        this.current_user = current_user;
        this.term = term;
        this.co = co;
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblAssignedCName = new javax.swing.JLabel();
        lblname1 = new javax.swing.JLabel();
        lblAssignedTerm = new javax.swing.JLabel();
        lblname2 = new javax.swing.JLabel();
        lblAssignedRanking = new javax.swing.JLabel();
        lblname3 = new javax.swing.JLabel();
        lblAssignedPName = new javax.swing.JLabel();
        lblname4 = new javax.swing.JLabel();
        lblAssignedPrating = new javax.swing.JLabel();
        lblname5 = new javax.swing.JLabel();
        lblAssignedschedule = new javax.swing.JLabel();
        btnEnrollCourse = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Details");

        lblname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname.setText("Name:");

        lblAssignedCName.setText("name");

        lblname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname1.setText("Term:");

        lblAssignedTerm.setText("name");

        lblname2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname2.setText("Ranking:");

        lblAssignedRanking.setText("name");

        lblname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname3.setText("Professor name:");

        lblAssignedPName.setText("name");

        lblname4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname4.setText("Professor rating:");

        lblAssignedPrating.setText("name");

        lblname5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname5.setText("schedule:");

        lblAssignedschedule.setText("name");

        btnEnrollCourse.setBackground(new java.awt.Color(153, 204, 255));
        btnEnrollCourse.setText("Enroll");
        btnEnrollCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollCourseActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedCName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblname3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblname4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAssignedPrating, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAssignedPName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblname5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblAssignedschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnEnrollCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(lblAssignedCName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname1)
                    .addComponent(lblAssignedTerm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname2)
                    .addComponent(lblAssignedRanking))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname3)
                    .addComponent(lblAssignedPName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname4)
                    .addComponent(lblAssignedPrating))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname5)
                    .addComponent(lblAssignedschedule))
                .addGap(35, 35, 35)
                .addComponent(btnEnrollCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(624, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrollCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollCourseActionPerformed
        // TODO add your handling code here:
        MainFrame.mfInstance.enrollNewStudent(co, current_user);
        JOptionPane.showMessageDialog(this, "Successfully enrolled");
        MainFrame.mfInstance.setLandingPage(current_user);
    }//GEN-LAST:event_btnEnrollCourseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainFrame.mfInstance.setLandingPage(current_user);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnrollCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAssignedCName;
    private javax.swing.JLabel lblAssignedPName;
    private javax.swing.JLabel lblAssignedPrating;
    private javax.swing.JLabel lblAssignedRanking;
    private javax.swing.JLabel lblAssignedTerm;
    private javax.swing.JLabel lblAssignedschedule;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname3;
    private javax.swing.JLabel lblname4;
    private javax.swing.JLabel lblname5;
    // End of variables declaration//GEN-END:variables
    public void fillData(){
        lblAssignedCName.setText(co.getCourseName());
        lblAssignedPName.setText(co.getProfessor().getName());
        lblAssignedPrating.setText(String.valueOf(co.getProfessor().getRating()));
        lblAssignedRanking.setText(String.valueOf(co.getRanking()));
        lblAssignedTerm.setText(co.getTerm().getName());
        lblAssignedschedule.setText(co.getSchedule());
    }
}
