/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Course.Course;
import Business.Course.CourseCatalog;
import Business.Course.Term;
import Business.User.User;
import UserInterface.MainFrame;

/**
 *
 * @author saurabhsrivastava
 */
public class CreateCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCourseJPanel
     */
    
    CourseCatalog courselist;
    Term term;
    public User current_user;
    
    public CreateCourseJPanel(CourseCatalog courselist, Term term, User current_user) {
        initComponents();
        
        this.courselist = courselist;
        this.term = term;
        this.current_user=current_user;
        populateTable();
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcoursename = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtcredit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcourse = new javax.swing.JTable();
        btnselectforterm = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Code:");

        jLabel2.setText("Price");

        jLabel3.setText("Credit:");

        jLabel4.setText("Name:");

        txtcoursename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcoursenameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Add Course");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create Course");

        tblcourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Code", "Price", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcourse);
        if (tblcourse.getColumnModel().getColumnCount() > 0) {
            tblcourse.getColumnModel().getColumn(0).setResizable(false);
            tblcourse.getColumnModel().getColumn(1).setResizable(false);
            tblcourse.getColumnModel().getColumn(2).setResizable(false);
            tblcourse.getColumnModel().getColumn(3).setResizable(false);
        }

        btnselectforterm.setBackground(new java.awt.Color(153, 204, 255));
        btnselectforterm.setText("Select For Fall");
        btnselectforterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectfortermActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(153, 153, 153));
        btnback.setText("< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnback)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcoursename, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcredit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(35, 35, 35)
                                .addComponent(btnselectforterm)
                                .addGap(27, 27, 27)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcoursename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnselectforterm)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcoursenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcoursenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoursenameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
        Double price = Double.parseDouble(txtprice.getText());
        String coursename = txtcoursename.getText();
        int credit = Integer.parseInt(txtcredit.getText());
        String code = txtcode.getText();
        
        
        Course cl = new Course();

        
        cl.setCode(code);
        cl.setCoursename(coursename);
        cl.setCredit(credit);
        cl.setPrice(price);
        courselist.addNewCourse(cl);
        
        ArrayList<Course> list =  this.term.getProfessorCourseMap().getOrDefault(this.current_user, new ArrayList<>());
        list.add(cl);
        this.term.getProfessorCourseMap().put(this.current_user,list);
        JOptionPane.showMessageDialog(this, "Course Updated");
        
        txtcode.setText("");
        txtcoursename.setText("");
        txtcredit.setText("");
        txtprice.setText("");
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnselectfortermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectfortermActionPerformed
        // TODO add your handling code here:
      int selectedRow = tblcourse.getSelectedRow();
      
    
    if (selectedRow == -1) {
        
        JOptionPane.showMessageDialog(this, "Please select a course to add to the term.");
    } else {
        Course newcourse = new Course();
        DefaultTableModel model = (DefaultTableModel) tblcourse.getModel();
        newcourse.setCoursename((String)model.getValueAt(selectedRow,0));
        newcourse.setCode((String)model.getValueAt(selectedRow,1));
        newcourse.setPrice((Double)model.getValueAt(selectedRow,2));
        newcourse.setCredit((Integer)model.getValueAt(selectedRow,3));
      
       
        
        
        term.addNewCourseOffering(newcourse, current_user);
       
        
        JOptionPane.showMessageDialog(this, "Course added to the term.");
    }
    }//GEN-LAST:event_btnselectfortermActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        MainFrame.mfInstance.setLandingPage(current_user);
    }//GEN-LAST:event_btnbackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblcourse.getSelectedRow();
        if (selectedRow == -1) {
        
        JOptionPane.showMessageDialog(this, "Please select a course to add to the term.");
    }
        else{
            ArrayList<Course> courseList = this.term.getProfessorCourseMap().getOrDefault(this.current_user, new ArrayList<>());
            DefaultTableModel model = (DefaultTableModel) tblcourse.getModel();
            String courseCode = (String)model.getValueAt(selectedRow, 1);
            for(int i=0;i<courseList.size();i++){
                if (courseList.get(i).getCode().equals(courseCode)){
                    courseList.remove(i);
                    break;
                }
            }
        populateTable();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnselectforterm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcourse;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtcoursename;
    private javax.swing.JTextField txtcredit;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblcourse.getModel();
        model.setRowCount(0);
        ArrayList<Course> list = this.term.getProfessorCourseMap().get(this.current_user);
        for (Course c : list){
        
            Object[] row = new Object[4];
            row[0] = c.getCoursename();
            row[1] = c.getCode();
            row[2] = c.getPrice();
            row[3] = c.getCredit();
            
            
            model.addRow(row);
        
        
        
        }   
        
}
}
